# Generated by Django 5.2.7 on 2025-11-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfinanciera',
            name='default_ahorro_y_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_ahorro_y_deuda_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_alimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_alimento_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_productos_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_sobrante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configfinanciera',
            name='default_sobrante_fijo',
            field=models.BooleanField(default=False),
        ),
    ]
