# Generated by Django 5.2.7 on 2025-12-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_configfinanciera_default_ahorro_y_deuda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrofinanciero',
            old_name='monto_fijo',
            new_name='productos_fijo',
        ),
    ]
