# Generated by Django 5.2.7 on 2025-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_rename_monto_fijo_registrofinanciero_productos_fijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfinanciera',
            name='fecha_inicio_registros',
            field=models.DateField(blank=True, null=True),
        ),
    ]
